
name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install openssh-client -y

      - name: Copy files to EC2 instances
        env:
          KEY: ${{ ec2-35-94-46-124.us-west-2.compute.amazonaws.com }}
          HOST_1: ec2-user@35.94.46.124
          HOST_2: ec2-user@34.217.70.174
          HOST_3: ec2-user35.167.86.222
        run: |
          echo "$KEY" > key.pem
          chmod 400 key.pem
          scp -o StrictHostKeyChecking=no -i key.pem -r * $HOST_1:/var/www/html/
          scp -o StrictHostKeyChecking=no -i key.pem -r * $HOST_2:/var/www/html/
          scp -o StrictHostKeyChecking=no -i key.pem -r * $HOST_3:/var/www/html/
